version: "3.9"

services:
  app:
    build: .
    container_name: gpt2-flask-app
    ports:
      - "9001:9001"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: gpt2-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
